name: Build & push
on:
  push:
    branches:
      - main
    paths:
      - "dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dev
        run: |
          docker build -t leocavalcante/dwoole:dev dev
          docker push leocavalcante/dwoole:dev
